NPCの機能
VGA-GLAB/2024-G-Lab-Team_B pull request #74
Opened 2024-06-01 08:27 UTC by ShigemaFuka

・名誉教授、警備員の追加機能

2024-06-02 04:19 UTC, GotouTamaki requested changes

2024-06-02 04:19 UTC, GotouTamaki commented on Assets/Scripts/NPC/ClosureRoad.cs
> +    [Tooltip("行き止まり中")] private bool _isClosure = default;
Tooltip属性のみでSerializeFilde属性が無い変数がありますが必要ではないですか？
特に_cardkeyは必要なように見えます。

2024-06-02 04:19 UTC, GotouTamaki commented on Assets/Scripts/NPC/Witness.cs
> +    #endregion
ここにもTooltip属性のみの変数ありますが、必要が無いなら属性を消した方が良いです。
また、属性付きは属性付き、無いものは無いものでまとめたほうが見やすいです。

2024-06-02 04:20 UTC, GotouTamaki commented on Assets/Scripts/NPC/Witness.cs
> +    [Tooltip("発見されたか")] private bool _isWitness = default;
ここにもTooltip属性のみの変数ありますが、必要が無いなら属性を消した方が良いです。
また、属性付きは属性付き、無いものは無いものでまとめたほうが見やすいです。

2024-06-03 05:58 UTC, ShigemaFuka commented on Assets/Scripts/NPC/ClosureRoad.cs
> +    [Tooltip("行き止まり中")] private bool _isClosure = default;
・[Tooltip("行き止まり中")]の削除

2024-06-05 04:56 UTC, GotouTamaki approved these changes

2024-06-05 04:56 UTC, merged